- name: Deploy Ecosistema Completo con Docker Compose
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACK_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "cat <<EOF > docker-compose.yml
          version: \"3.8\"
          services:
            db-mysql:
              image: mysql:8.0
              container_name: mysql-db
              restart: always
              environment:
                MYSQL_DATABASE: despacho_db
                MYSQL_ROOT_PASSWORD: root_password
              ports:
                - \"3306:3306\"

            back-ventas:
              image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_VENTAS }}:latest
              container_name: ventas-container
              depends_on:
                - db-mysql
              ports:
                - \"8081:8080\"
              environment:
                - DB_ENDPOINT=db-mysql
                - DB_PORT=3306
                - DB_NAME=despacho_db
                - DB_USERNAME=root
                - DB_PASSWORD=root_password

            back-despachos:
              image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_DESPACHOS }}:latest
              container_name: despachos-container
              depends_on:
                - db-mysql
              ports:
                - \"8082:8080\"
              environment:
                - DB_ENDPOINT=db-mysql
                - DB_PORT=3306
                - DB_NAME=despacho_db
                - DB_USERNAME=root
                - DB_PASSWORD=root_password
          EOF",
              "docker-compose up -d"
            ]}'